# Generated by Django 5.2 on 2025-05-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatapp', '0002_alter_tbl_chat_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_chat',
            name='file',
        ),
        migrations.AddField(
            model_name='tbl_chat',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_chat',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tbl_chat',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_chat',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
