# Generated by Django 5.1.3 on 2024-11-27 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_chat',
        ),
    ]
