# Generated by Django 5.2 on 2025-04-29 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
        ('User', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_chat',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_chat',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tbl_chat',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_chat',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_chat',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tbl_chat',
            name='reciver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='Guest.tbl_user'),
        ),
        migrations.AlterField(
            model_name='tbl_chat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='Guest.tbl_user'),
        ),
    ]
