# Generated by Django 5.2 on 2025-04-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
        ('User', '0004_tbl_chat_file_data_tbl_chat_file_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_chat',
            new_name='tbl_chatold',
        ),
    ]
